### ISSUE TITLE
v1.0.2 release checklist

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/dime#65]
- [x] update fifa20
- [x] unify python pipelines with dalex notebook
- [ ] update gifs
- [x] update dashboards
- [x] test examples
- [x] test vignettes
- [x] `rhub::check_for_cran()`
- [x] `rhub::check_with_rdevel()`
- [x] `usethis::use_cran_comments()`
- [x] `devtools::submit_cran()`
- [x] accept the mail
- [x] tag release on GitHub
