### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/dime#66]
- [x] change mlr? example to the regression model on `DALEX::apartments`
- [x] change sklearn? example to the regression model on `dalex fifa`
- [x] use `Explainer.dump()` in python examples
- [x] use `ranger` instead of `randomForest` (everywhere)
- [x] `pip install dalex` console chunk
- [x] update gifs 
- [x] add parsnip example
- [x] use macos devel in gh-actions
- [x] citation 
- [x] change default `B = 10`, `N = 300` to support "fast feedback loop" process
- [x] add `N/n_samples` to `feature_importance` calculation
- [x] remove d3 from DESC and README
- [x] remove txtProgressBar import
- [x] remove covr from suggests 
- [x] fix wrong vignette indexEntry p&r
- [x] write blog about IEMA
