### ISSUE TITLE
v1.1.0 release checklist

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/dime#67]
- [x] add `ms_update_options()` and `ms_update_observations()` to the perks vignette
- [x] test vignettes
- [x] update dashboards
- [x] `rhub::check_for_cran()`
- [x] `rhub::check_with_rdevel()`
- [x] `usethis::use_cran_comments()`
- [x] `devtools::submit_cran()`
- [x] accept the mail
- [x] tag release on GitHub
