### ISSUE TITLE
v1.2.0 release checklist

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/dime#72]
- [x] update fifa example
- [x] add info about interactive features to the `modelStudio()` documentation
- [x] test vignettes
- [x] update dashboards
- [x] `rhub::check_for_cran(env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always"))`
- [ ] ~`rhub::check_with_rdevel(env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always"))`~
- [x] `usethis::use_cran_comments()`
- [x] `devtools::submit_cran()`
- [x] accept the mail
- [x] tag release on GitHub
