### ISSUE TITLE
v2.0.0 release checklist

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/dime#86]
Due 02.09

- [x] #85 
- [x] #82 
- [x] update the `DALEX` dependency to `2.0.0` and edit `NEWS.md` #87 
- [x] add `tidymodels` example 
- [x] test examples
- [x] test vignettes
- [x] update dashboards
- [x] check urls in doc for `https` and `/`
- [x] test Python vignettes and update dashboards
- [x] `rhub::check_for_cran(env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always"))`
- [x] `rhub::check_with_rdevel(env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always"))`
- [x] `usethis::use_cran_comments()`
- [x] `devtools::submit_cran()`
- [x] accept the mail
- [x] tag release on GitHub

**Comment by hbaniecki** [comment]
done
