### ISSUE TITLE
v2.1.0 release checklist

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/dime#95]
Due 20.11

- [x] test examples
- [x] test vignettes
- [x] update dashboards
- [x] test Python vignettes and update dashboards
- [x] `rhub::check_for_cran(env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always"))`
- [x] `rhub::check_with_rdevel(env_vars=c(R_COMPILE_AND_INSTALL_PACKAGES = "always"))`
- [x] `usethis::use_cran_comments()`
- [x] `devtools::submit_cran()`
- [x] accept the mail
- [x] tag release on GitHub
